"""AMD Strix Halo GEMM kernel APIs."""

from .api import explicit_mm, fused_swiglu_up_gate, mm
from .autotune import (
    AutotuneResult,
    RaggedAutotuneCandidate,
    RaggedAutotuneResult,
    RaggedDotMode,
    autotune,
    autotune_ragged_dot,
    default_ragged_dot_candidates,
    find_autotune_candidates,
    generated_shape_for_kernel,
)
from .benchmarking import BenchmarkDatabase, BenchmarkRecord, BenchmarkShape
from .metadata import (
    ACC_DTYPE,
    ARCH,
    RHS_SUBCHANNEL_SCALE_LAYOUT,
    SCALE_DTYPE_BF16,
    SUPPORTED_GEMM_LAYOUTS,
    SUPPORTED_SUBCHANNELS,
    Epilogue,
    GemmLayout,
    KernelMetadata,
    KernelSchedule,
    KernelStatus,
    OperandDType,
    ScaleMode,
    ScaleSpec,
    TileConfig,
)
from .native import (
    NativeRuntimeStatus,
    amdgcn_metadata_dir,
    amdgcn_metadata_path_for_kernel_id,
    dispatch_runtime_status,
    hsaco_dir,
    hsaco_path_for_kernel_id,
    launch_generated_kernel,
    launch_hsaco,
    native_library_path,
)
from .ragged import (
    RaggedBwdDotConfig,
    RaggedDotConfig,
    RaggedGroupInfo,
    calculate_group_info,
    ragged_dot_int4_bwd,
    ragged_dot_int4,
)
from .registry import KernelRegistry, default_registry
from .torch_ops import TORCH_GEMM_OP, TORCH_OP_NAMESPACE, register_torch_ops, torch_gemm

__all__ = [
    "ACC_DTYPE",
    "ARCH",
    "AutotuneResult",
    "BenchmarkDatabase",
    "BenchmarkRecord",
    "BenchmarkShape",
    "RHS_SUBCHANNEL_SCALE_LAYOUT",
    "SCALE_DTYPE_BF16",
    "SUPPORTED_GEMM_LAYOUTS",
    "SUPPORTED_SUBCHANNELS",
    "Epilogue",
    "GemmLayout",
    "KernelMetadata",
    "KernelRegistry",
    "KernelSchedule",
    "KernelStatus",
    "NativeRuntimeStatus",
    "OperandDType",
    "RaggedAutotuneCandidate",
    "RaggedAutotuneResult",
    "RaggedBwdDotConfig",
    "RaggedDotMode",
    "RaggedDotConfig",
    "RaggedGroupInfo",
    "ScaleMode",
    "ScaleSpec",
    "TileConfig",
    "TORCH_GEMM_OP",
    "TORCH_OP_NAMESPACE",
    "amdgcn_metadata_dir",
    "amdgcn_metadata_path_for_kernel_id",
    "autotune",
    "autotune_ragged_dot",
    "calculate_group_info",
    "default_registry",
    "default_ragged_dot_candidates",
    "dispatch_runtime_status",
    "explicit_mm",
    "find_autotune_candidates",
    "fused_swiglu_up_gate",
    "generated_shape_for_kernel",
    "hsaco_dir",
    "hsaco_path_for_kernel_id",
    "launch_generated_kernel",
    "launch_hsaco",
    "mm",
    "native_library_path",
    "ragged_dot_int4_bwd",
    "ragged_dot_int4",
    "register_torch_ops",
    "torch_gemm",
]
